[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[dev]
 command = "vite dev"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200